### ISSUE TITLE
Special rules to clear document title for querying ADS database

### ISSUE THREAD

**Issue by stevenlujpl** [USCDataScience/parser-indexer-py#27]
**Rule 1**: it seems that documents whose titles contain `?` are causing problems to query ADS database. The following Solr JIRA ticket indicates that this might be a bug in Solr. The Solr JIRA ticket was last updated in April 2020. **We will remove all `?` in the document titles.**

https://issues.apache.org/jira/browse/SOLR-4457

For example:

When querying the ADS database using the following two titles, the ADS database returns nothing. 

```
1.  ROCKS OF ANDESITIC COMPOSTION AT THE MARS PATHFINDER SITE: WHAT DO THEY MEAN?
2. THARSIS MONTES AS COMPOSITE VOLCANOES?: 2. LINES OF EVIDENCE FOR EXPLOSIVE VOLCANISM IN FAR-FIELD DEPOSITS
```

However, if we remove the `?` in the titles, the queries worked.

**Comment by stevenlujpl** [comment]
**Rule 2: searching ADS DB with all lower case titles.**

The titles of the LPSC abstracts are all upper case. However, it seems sometimes the ADS DB returns nothing when searched with all upper case titles, however, if I convert all upper case titles to all lower case titles, then the ADS DB worked. 

For example: 

When searching ADS DB with the title below, it returns nothing. However, if I convert the title to all lower cases, then it worked. 

```
Ni IN THE SOIL OF MARS: A CHRONOMETER TO MEASURE THE GLOBAL SOIL PRODUCTION RATE AND IMPLICATIONS FOR EXOBIOLOGY
```

**Comment by wkiri** [comment]
Wow, these are both bizarre!  Thanks for identifying some work-arounds.

**Comment by stevenlujpl** [comment]
Rule 3: When a title contains a period at the end, grobid tool consistently extracts the title with the period and the first character of the author's name. For example, the title, author names, and affiliations of a LPSC abstract (1998_1589.pdf) look like below:

```
IMPLICATIONS OF THE APPARENT ABSENCE OF MAARS IN VIKING ORBITER
IMAGERY. K. L. Mitchell and L. Wilson, Environmental Science
Department, Institute of Environmental and Natural Sciences,
Lancaster University, Lancaster LA1 4YQ, UK (K.L.Mitchell@lancaster.ac.uk).
```

The title extracted by the grobid tool is:
```
IMPLICATIONS OF THE APPARENT ABSENCE OF MAARS IN VIKING ORBITER IMAGERY. K
```

We need to remove ". K" before searching the ADS database.

**Comment by stevenlujpl** [comment]
Rule 4: remove LPSC header in grobid titles. 

Sometimes the grobid titles extracted contain LPSC header (see the following examples), and we need to remove the LPSC header before querying the ADS DB.

```
1. ORIENTATION OF AEOLIAN FLUTES AT THE MARS PATHFINDER LANDING SITE Lunar and Planetary Science XXIX 1530.pdf
2. THE MARTIAN SURFACE BOUNDARY LAYER: HEAT AND MOMENTUM FLUX RESULTS FROM MARS Lunar and Planetary Science XXIX 1858.pdf
3. THE EFFECT OF THIN COATINGS OF DUST OR SOIL ON THE BULK APXS COMPOSITION OF THE UNDERLYING ROCKS AT THE PATHFINDER LANDING SITE. Lunar and Planetary Science XXIX 1962.pdf
4. A B Lunar and Planetary Science XXX 1057.pdf
5. Rock Coatings at the Mars Pathfinder Landing Site. Lunar and Planetary Science XXXI 1262.pdf
6. NEAR-SURFACE WIND SPEEDS INFERRED FROM MOVEMENT OF SAND GRAINS OBSERVED BY SPIRIT IN GUSEV CRATER, MARS. Lunar and Planetary Science XXXIX (2008) 2218.pdf
```

**Comment by stevenlujpl** [comment]
Rule 5: Add double quotes around the title if the title contains the Lucene reserved keywords "NEAR" and "NOT".

There are more Lucene reserved keywords, but it seems only "NEAR" and "NOT" are causing problems to ADS Solr queries. For now, we will only escape "NEAR" and "NOT".
