### ISSUE TITLE
Update `process` functions to handle recent ADS parser updates

### ISSUE THREAD

**Issue by wkiri** [USCDataScience/parser-indexer-py#35]
@wkiri I haven't confirmed it yet, but I think if the change I made in ADS parser breaks the `process` function in JSRE parser, it most likely breaks the `process` functions in other parsers except `lpsc_parser.py`. The functionalities in the Class definitions should be fine.  This means if you directly run a parser other than LPSC parser, it most likely will fail. 

Everything in LPSC parser should work properly. I think this is what we need for now. I will fix the problems in other parsers after I come back from vacation.

_Originally posted by @stevenlujpl in https://github.com/USCDataScience/parser-indexer-py/issues/25#issuecomment-885075111_

**Comment by stevenlujpl** [comment]
@wkiri This problem was fixed by the commit (24dfc1bb8f077221d729132582aa495cedec4a51) I made yesterday when I tested the journal papers. 

Please do a `git pull` for the MTE repo in /proj/mte/.
