### ISSUE TITLE
Cannot load new NER classifier

### ISSUE THREAD

**Issue by wkiri** [USCDataScience/parser-indexer-py#37]
I find that I am unable to use our system with the new NER model that I trained.  I am doing this work on `mlia-compute1`.

It works when I use it from CoreNLP via Java:
```Console
$ java -cp ".:/proj/mte/stanford-corenlp-mte-4.2.0/*" edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier /proj/mte/trained_models/ner_MERA+property.ser.gz -testFile all-files-property.tsv 
```

However, I get a runtime error when it is called with `self.corenlp.annotate()` in `corenlp_parser.py` from here:

```Console
$ python /proj/mte/parser-indexer-py/src/parserindexer/lpsc_parser.py -i /proj/mte/data/corpus-lpsc/mer-pdf/2004_1093.pdf -o mer-a-jsre-test.jsonl -jr /proj/mte/jSRE/jsre-1.1 -jm /proj/mte/trained_models/jSRE-lpsc15-merged-binary.model -n /proj/mte/trained_models/ner_MERA+property.ser.gz
```
Output:
```
edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from /proj/mte/trained_models/ner_MERA property.ser.gz
```
Note: I added a `print(output)` statement to `corenlp_parser.py` to see this result; otherwise we do not see any error message but instead the code fails when it tries to access 'sentences'.

I thought it might be the "+" character in the filename, but even if I rename the file, I get the same error.

The same command runs to completion with the PHX NER model:
```
$ python /proj/mte/parser-indexer-py/src/parserindexer/lpsc_parser.py -i /proj/mte/data/corpus-lpsc/mer-pdf/2004_1093.pdf -o mer-a-jsre-test.jsonl -jr /proj/mte/jSRE/jsre-1.1 -jm /proj/mte/trained_models/jSRE-lpsc15-merged-binary.model -n /proj/mte/trained_models/phx_ner_train_lpsc15n16_emt_gazette.ser.gz 
```
(please note, this will be spammy because of the print statement I added above.  However, there is no runtime error loading the NER model.)

I trained this model with CoreNLP 4.2.0:
```Console
$ train_ner.py all-files-property.list corenlp.prop MERA_targets_minerals-2017-05_elements.gaz.txt  ner_MERA+property.ser.gz -t
```

One difference is that this model contains the Property entity type, and the model file is a lot larger (88MB vs. 27MB for PHX, in `.gz` form).  Also, I am not sure which version of CoreNLP was active when I trained the (working) PHX model (file is dated Nov. 30, 2020; was this before or after we upgraded CoreNLP to 4.2?).  Still, it seems odd that the current CoreNLP would read the old model file fine, but not the new one.   Is it possible that some portion of the system is out of date or needs restarting?  Ideas welcome!

**Comment by stevenlujpl** [comment]
@wkiri I just looked into this problem. I haven't exactly figured out the reason yet, but I suspect the problem is related to the difference (maybe the Property entity type) in the input files. I am running out of time today, and I will continue tomorrow. Please see below for the summary of the things that I have confirmed:

1. I can reproduce the error
2. `train_ner.py`, `train_corenlp_ner.sh`, and `lpsc_parser.py` scripts work fine on MSL LPSC docs. I trained two NER models using `train_ner.py` and `train_corenlp_ner.sh` scripts, and they both work fine for `lpsc_parser.py`. Please note that I used corenlp 4.2 to train the two NER models.
3. NER models trained using MER A docs don't work for `lpsc_parser.py`. Similarly, I trained two NER models with `train_ner.py` and `train_corenlp_ner.sh` on 10 MER A docs, and they both don't work for `lpsc_parser.py` (i.e., got the same IOException). Here, I think I can say that model size isn't the problem because the two models I trained are only ~10M. 

This is where I am now. Next, I will remove the Property entities from the 10 MER A docs I used, and train two NER models with `train_ner.py` and `train_corenlp_ner.sh` and see if they work with `lpsc_parser.py` or not. If so, then the IOException is somehow related to the Property entities and I will look into solutions to fix the problem.

**Comment by wkiri** [comment]
@stevenlujpl Thank you for this investigation!  

I tried training a new NER model with only 10 training files and without the `Property` entity type.  I still get the "Couldn't load classifier" error (but the model works fine when calling CoreNLP through Java).  Let's keep investigating this!

**Comment by wkiri** [comment]
Oh wow, I think I figured it out.  In CoreNLP 4.2, the NER model should be specified in the properties dictionary with the name `ner_model` instead of `ner.model`.  It is puzzling that storing older models in `ner.model` did still seem to work.

**Comment by wkiri** [comment]
No, this is not right.  Still investigating.

**Comment by stevenlujpl** [comment]
This is very interesting. I tried using `ner_model` option with the models I trained yesterday, and they indeed are working. I wonder where did you find the information about `ner_model`. Please see the Options table from the following link on the Stanford CoreNLP website. It still lists `ner.model` as the option to load the self-trained NER model.

**Comment by stevenlujpl** [comment]
Forgot to put in the link. Here it is. https://stanfordnlp.github.io/CoreNLP/ner.html#options

**Comment by wkiri** [comment]
Yes, things were working so I thought `ner_model` was correct.  Instead, with `ner.model` not specified, CoreNLP is falling back to some kind of default NER model, or possibly the last one specified to the server?  I cannot tell.  At any rate, you do not get the classifier loading error, but it is not using the custom NER model when you use `ner_model`.  I think this is ignored.

**Comment by stevenlujpl** [comment]
I tried using `ner+model`, and the outputs look similar to the output of using `ner_model`. One strange thing is that when I use `ner+model` or `ner_model` option, corenlp is still able to classify words as `Element`.

**Comment by wkiri** [comment]
I agree.  It is somehow accessing a NER model even when it is not specified.  I wonder which model it is?

**Comment by wkiri** [comment]
Aha, I think it is using
> ner.model = ner_model_train_62r15v3_emt_gazette.ser.gz

from `/proj/mte/stanford-corenlp-mte-4.2.0/StanfordCoreNLP.properties`, since that is how we start it up.

**Comment by stevenlujpl** [comment]
I was going to say the same thing. This would explain why the default NER model can still tag words as `Element`.

**Comment by wkiri** [comment]
Still, the classifier can be loaded fine from the Java interface:
```Console
$ java -cp ".:/proj/mte/stanford-corenlp-mte-4.2.0/*" edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier /proj/mte/trained_models/ner_MERA+property.ser.gz -testFile all-files-10.tsv > t.log
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - Invoked on Wed Aug 04 09:49:29 PDT 2021 with arguments: -loadClassifier /proj/mte/trained_models/ner_MERA+property.ser.gz -testFile all-files-10.tsv
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - testFile=all-files-10.tsv
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - loadClassifier=/proj/mte/trained_models/ner_MERA+property.ser.gz
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from /proj/mte/trained_models/ner_MERA+property.ser.gz ... done [4.5 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - CRFClassifier tagged 15773 words in 10 documents at 12568.13 words per second.
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Entity    P       R       F1      TP      FP      FN
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -         Element    0.9547  0.9872  0.9707  232     11      3
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -         Mineral    0.9752  0.9833  0.9793  118     3       2
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -        Property    0.0000  1.0000  0.0000  0       28      0
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Target    1.0000  1.0000  1.0000  97      0       0
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Totals    0.9141  0.9889  0.9501  447     42      5
```
We only get the "failed to load" error when using the Python interface.

**Comment by wkiri** [comment]
Today we figured out that:
* Model file must be accessible to `mteuser` (who runs the CoreNLP server), i.e. world-readable or group-readable for group `mte`
* But we don't know why model with Property works in call from Java but not in call from Python
    * [ ] Kiri: Training on same docs without Property class in Python
    * [ ] Steven: look at Java code for -loadClassifier, Python API for annotate()

**Comment by wkiri** [comment]
I just trained a NER model using the last 10 docs in my list, which are all PHX labeled docs.  This document set includes Property entities.  This model works with CoreNLP in Python!   I will continue testing.

**Comment by wkiri** [comment]
I did this with the last 500 documents and it still worked.  I am now re-training from scratch with all 1099 documents and will share the outcome.

**Comment by wkiri** [comment]
Wow, it works!

The only thing I changed is to specify that the output model filename is `ner_MERA-property.ser.gz` instead of `ner_MERA+property.ser.gz`.  Earlier when I was concerned that the "+" in the filename might be the problem, I used `mv` to change the name of the file to omit the "+".  This still did not work.  I now suspect that the original filename is somehow encoded inside the `.ser` file, and it was causing problems when called through the Python API, which (as noted above) somehow loses the "+" character!

Here are the tests I did:
1. Train without "+" in NER filename works:

```Console
$ ../../git/src/train_ner.py all-files.list /proj/mte/trained_models/corenlp_ner.prop MERA_targets_minerals-2017-05_elements.gaz.txt ner_MERA-property.ser.gz -t
```

Test in Python:

```Python
>>> corenlp = StanfordCoreNLP('http://localhost:9000')
>>> props = {'ner.model': '/proj/mte/trained_models/ner_MERA-property.ser.gz', 'annotators': 'ner', 'outputFormat': 'json'}
>>> s = corenlp.annotate('The WW target is basaltic', properties=props)
>>> s
{u'sentences': [{u'tokens': [{u'index': 1, u'word': u'The', u'lemma': u'the', u'after': u' ', u'pos': u'DT', u'characterOffsetEnd': 3, u'characterOffsetBegin': 0, u'originalText': u'The', u'ner': u'O', u'before': u''}, {u'index': 2, u'word': u'WW', u'lemma': u'WW', u'after': u' ', u'pos': u'NNP', u'characterOffsetEnd': 6, u'characterOffsetBegin': 4, u'originalText': u'WW', u'ner': u'Target', u'before': u' '}, {u'index': 3, u'word': u'target', u'lemma': u'target', u'after': u' ', u'pos': u'NN', u'characterOffsetEnd': 13, u'characterOffsetBegin': 7, u'originalText': u'target', u'ner': u'O', u'before': u' '}, {u'index': 4, u'word': u'is', u'lemma': u'be', u'after': u' ', u'pos': u'VBZ', u'characterOffsetEnd': 16, u'characterOffsetBegin': 14, u'originalText': u'is', u'ner': u'O', u'before': u' '}, {u'index': 5, u'word': u'basaltic', u'lemma': u'basaltic', u'after': u'', u'pos': u'JJ', u'characterOffsetEnd': 25, u'characterOffsetBegin': 17, u'originalText': u'basaltic', u'ner': u'Property', u'before': u' '}], u'index': 0, u'entitymentions': [{u'tokenBegin': 1, u'tokenEnd': 2, u'docTokenBegin': 1, u'characterOffsetEnd': 6, u'docTokenEnd': 2, u'text': u'WW', u'characterOffsetBegin': 4, u'nerConfidences': {u'Target': 0.99634979620502}, u'ner': u'Target'}, {u'tokenBegin': 4, u'tokenEnd': 5, u'docTokenBegin': 4, u'characterOffsetEnd': 25, u'docTokenEnd': 5, u'text': u'basaltic', u'characterOffsetBegin': 17, u'nerConfidences': {u'Property': 0.95285121801604}, u'ner': u'Property'}]}]}
```

2. Train with "+" in NER filename leads to failure:

```Console
$ ../../git/src/train_ner.py all-files.list /proj/mte/trained_models/corenlp_ner.prop MERA_targets_minerals-2017-05_elements.gaz.txt ner_MERA+property.ser.gz -t
```

Test in Python:
```Python
>>> corenlp = StanfordCoreNLP('http://localhost:9000')
>>> props = {'ner.model': '/proj/mte/trained_models/ner_MERA+property.ser.gz', 'annotators': 'ner', 'outputFormat': 'json'}
>>> s = corenlp.annotate('The WW target is basaltic', properties=props)
>>> s
u"edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from /proj/mte/trained_models/ner_MERA property.ser.gz"
```
Notice that "+" is missing from the error message.

I will close this issue.  I left the `ner_MERA+property.ser.gz` file in `/proj/mte/trained_models/` for now in case it is worth examining.  However, we should use `ner_MERA-property.ser.gz` for any actual runs.

**Comment by stevenlujpl** [comment]
@wkiri I am so glad you figured it out! I am actually even more confused by comparing what I learned from the source code to your experiment results. I won't investigate further since you already got the model working.

**Comment by wkiri** [comment]
@stevenlujpl Now you are making me curious about what you found! :)

**Comment by stevenlujpl** [comment]
@wkiri What I learned from reading the source code is that the Java and Python commands seem to land at the same `loadClassifier()` function in `CRFClassifier.java`. In order to be 100% certain about the Java and Python commands are actually calling the same `loadClassifier()` function, I will need to add some debug statements in the Java code, re-compile the .java source code to .class files, and then package them up into a jar file. This will take some time as I haven't worked in the Java world for a long time. The Java command is extremely easy to follow, but the Python command isn't as it is calling CoreNLP through a server pipeline. 

Since this will be time-consuming (I think it is going to take me at least a day to figure it out) and you've had the model working, I think we should stop here unless you think we need to understand the root cause. Please let me know what you think. Thanks.

**Comment by wkiri** [comment]
@stevenlujpl Thanks for sharing what you learned!  I agree that it is not worth the extra effort to trace this through the Java and Python code.  We will plan to avoid "special" characters in NER model filenames.  I'm not sure what the full set of special characters would be, so for now, I think it is good for us to be aware that if we see this error, we should suspect a filename problem.  By the way, since the `annotate()` function returns either a dictionary (on success) or a string (on failure), perhaps we could add a check to see if it is string type, and if so, print it out (and exit with error - raise exception).  Otherwise the error message is invisible and the code crashes when trying to access the "sentences" field of the dict (which is a string).  What do you think?

**Comment by stevenlujpl** [comment]
@wkiri Agreed. In terms of the "special" characters, I think as long as we only use underscores and hyphens, we should be fine. 

I also think it is necessary to capture the corenlp exceptions. The method of checking dict vs string should work. I will add a check there, and if annotate() function fails, I will throw a RuntimeError message from the python scripts. 

In my opinion, corenlp really should throw exceptions instead of returning the exception message as a string. In the corenlp source code, they are calling the `loadClassifierNoExceptions()` function that has a `try-catch` block to suppress the exceptions thrown from the `loadClassifier()` function.

**Comment by wkiri** [comment]
@stevenlujpl I agree with you 100%!
